### PR TITLE
Update jquery, use bootstrap from CDN

### PR DESCRIPTION
**Pull request by santhoshtr**

### CODE REVIEW

**Comment by Nikerabbit** [comment]
```
ERROR
>> Message: Arabic decimal plural test for one
>> Actual: "one"
>> Expected: "other"
```

I thought you fixed this already, do you know why this is happening?

**Comment by santhoshtr** [comment]
That is wierd. It was fixed in 0f8f7664794394ecb6e3b635b058f4a2f0c34a48

**Comment by Nikerabbit** [comment]
This one is coming from the plural rule parser I think. Did you check whether it was fixed there?

**Comment by santhoshtr** [comment]
My commit had a dirty submodule for CLDRPluralParser. Updated now. All tests are passing

**Pull request merged**
