### PR TITLE
Update devDependencies packages

### PR DESCRIPTION
**Pull request by amire80**
eslint-config-wikimedia: 0.14.1 -> 0.15.3
eslint-plugin-qunit: 4.0.0 -> 4.2.0
grunt-eslint: 22.0.0 -> 23.0.0
jquery: 3.4.0 -> 3.5.1

### CODE REVIEW

**Comment by Nikerabbit** [comment]
Failure might be due to requiring eslint7, which no longer supports node 0.10.x. Some of the packages pull in eslint 7.1, as can be seen in package-lock.json. I think it's `grunt-eslint` and maybe others.

**Comment by amire80** [comment]
Mmmm... And do we need to support this version of node?

**Comment by Nikerabbit** [comment]
This isn't a node library, so no. I think it's only used for linting/testing. Latest version that Travis needs is sufficient.

**Comment by amire80** [comment]
OK, and do you know how to fix it?

**Comment by Nikerabbit** [comment]
I'd try updating https://github.com/wikimedia/jquery.i18n/blob/master/.travis.yml#L4

**Comment by amire80** [comment]
OK, done in https://github.com/wikimedia/jquery.i18n/pull/215

**Comment by amire80** [comment]
#215 appears to have fixed this issue, but created some others. I'm working on it.

**Pull request merged**
